evariables:
   - HOTROD_URL

variables:
   figsubprojects:
      - common
      - core
      - coreauth
      - logger
      - loggercache
      - loggertransport
      - loggerui
      - loggerauth

   gitblit_keys:
     admin_ssh: |
         {{ admin_public_ssh }}
        
     jenkins_ssh: |
        {{ jenkins_public_ssh }}
        
   jenkins_private_key: |
        {{ jenkins_private_ssh }}

   repos:   
      'github.com/panoptix-za':
          - docker-saltmaster
          - docker-gitblit
          - docker-grand-ambassador
          - docker-jenkins
          - docker-rundeck
          - docker-kibana
          - docker-sslrproxy
          - docker-modcasproxy
          - docker-cas
          - docker-ldap
          - docker-logstash
          - docker-jdk
          - docker-rsyslog

   repos_no_dockerfile:   
      'github.com/panoptix-za':
          - HotRod
          - hotrod-auth
          - hotrod-admin
          - cas-overlay
          - mini-templates
 

templates:
#  - src: fig.sh.orig
#    dst: fig.sh
  - src: hacking/repos.orig
    dst: hacking/repos
  - src: hacking/fig.yml.orig
    dst: hacking/fig.yml
#  - src: loggerauth/loggerauth_kibanarproxy/reverse.conf.orig
#    dst: loggerauth/loggerauth_kibanarproxy/reverse.conf
#  - src: coreauth/corejenkinsrproxy/reverse.conf.orig
#    dst: coreauth/corejenkinsrproxy/reverse.conf
#  - src: core/coregitblit/admin.keys.orig
#    dst: core/coregitblit/admin.keys
#  - src: core/corejenkins/id_rsa.orig
#    dst: core/corejenkins/id_rsa
#  - src: core/corejenkins/jenkins.model.JenkinsLocationConfiguration.xml.orig
#    dst: core/corejenkins/jenkins.model.JenkinsLocationConfiguration.xml

