evariables:
   - HOTROD_URL

variables:
  weave_shared_secret: {{ weave_shared_secret }}
  weave_master_ip: {{ weave_master_ip }}
  salt_user: {{ salt_user }}
  
  gitblit_keys:
    admin_ssh: |
      {{ admin_public_ssh }}
        
    jenkins_ssh: |
      {{ jenkins_public_ssh }}
        
    jenkins_private_key: |
      {{ jenkins_private_ssh }}

    repos:   
      'github.com/panoptix-za':
        - docker-cas
        - docker-coresaltmaster
        - docker-elasticsearch
        - docker-gitblit
        - docker-gitolite
        - docker-grand-ambassador
        - docker-jdk
        - docker-jenkins
        - docker-kibana
        - docker-ldap
        - docker-logstash
        - docker-modcasproxy
        - docker-rsyslog
        - docker-rundeck
        - docker-saltmaster
        - docker-sslrproxy

   repos_no_dockerfile:   
      'github.com/panoptix-za':
        - cas-overlay
        - mini-templates
        - hotrod-admin
        - hotrod-auth
        - hotrod-components
        - hotrod-jwt-proxy
        - hotrod-renderer
        - hotrod-reporting
        - hotrod-template

templates:
  - src: hacking/repos.orig
    dst: hacking/repos
  - src: hacking/fig.yml.orig
    dst: hacking/fig.yml
  - src: local/ldap/db.ldif.orig
    dst: local/ldap/db.ldif
  - src: local/auth/local.yml.orig
    dst: local/auth/local.yml
  - src: local/adminauth/local.yml.orig
    dst: local/adminauth/local.yml    
  - src: local/kibanaproxy/local.yml.orig
    dst: local/kibanaproxy/local.yml
  - src: local/git/gitblit.properties.orig
    dst: local/git/gitblit.properties
  - src: pillar/weave.sls.orig
    dst: pillar/weave.sls
  - src: salt/master.orig
    dst: salt/master
  - src: salt/master.d/weave.conf.orig
    dst: salt/master.d/weave.conf
  - src: project/containers/admin/local.yml.orig
    dst: project/containers/admin/local.yml
         
