evariables:
   - HOTROD_URL

variables:
   figsubprojects:
      - common
      - core
      - coreauth
      - logger
      - loggercache
      - loggertransport
      - loggerui
      - loggerauth

   gitblit_keys:
     admin_ssh: |
         {{ admin_public_ssh }}
        
     jenkins_ssh: |
        {{ jenkins_public_ssh }}
        
   jenkins_private_key: |
        {{ jenkins_private_ssh }}

   repos:   
      'github.com/panoptix-za':
          - docker-saltmaster
          - docker-gitblit
          - docker-grand-ambassador
          - docker-jenkins
          - docker-rundeck
          - docker-kibana
          - docker-sslrproxy
          - docker-modcasproxy
          - docker-cas
          - docker-ldap
          - docker-logstash
          - docker-jdk
          - docker-rsyslog
          - docker-coresaltmaster

   repos_no_dockerfile:   
      'github.com/panoptix-za':
          - HotRod
          - hotrod-auth
          - hotrod-admin
          - cas-overlay
          - mini-templates
 

templates:
  - src: hacking/repos.orig
    dst: hacking/repos
  - src: hacking/fig.yml.orig
    dst: hacking/fig.yml
  - src: local/ldap/db.ldif.orig
    dst: local/ldap/db.ldif
  - src: local/auth/local.yml.orig
    dst: local/auth/local.yml
  - src: local/adminauth/local.yml.orig
    dst: local/adminauth/local.yml    
  - src: local/kibanaproxy/local.yml.orig
    dst: local/kibanaproxy/local.yml
  - src: local/git/gitblit.properties.orig
    dst: local/git/gitblit.properties
  - src: project/containers/admin/local.yml.orig
    dst: project/containers/admin/local.yml
         
