variables:
  hotrod_project_name: {{ env['HOTROD_PROJNAME'] }}
  weave_shared_secret: {{ env['WEAVE_SECRET'] }}
  weave_master_ip: {{ env['HOTROD_HOSTNAME'] }}
  hotrod_admin: {{ env['HOTROD_ADMIN_SETTINGS'] }}
  hotrod_projectfs: {{ env['HOTROD_PROJECTFS'] }}
  hotrod_root_host: {{ env['HOTROD_HOSTNAME'] }}
  ldap_bind_user: cn=admin,dc=com  
  ldap_bind_pw: {{ env['LDAP_MANAGER_PASSWORD'] }}
  
  userauth:
    secret: {{ env['HOTROD_AUTH_SECRET'] }}
    url: http://{{ env['HOTROD_HOSTNAME'] }}:3001
    ldap_bind_user: cn=admin,dc=com
    ldap_bind_pw: {{ env['LDAP_MANAGER_PASSWORD'] }}
    
  adminauth:
    secret: {{ env['HOTROD_ADMIN_AUTH_SECRET'] }}
    url: http://{{ env['HOTROD_HOSTNAME'] }}:3002  
    ldap_bind_user: cn=admin,dc=com
    # HINT: Use the unencrypted version for now. FIXME
    ldap_bind_pw: {{ env['LDAP_MANAGER_PASSWORD'] }}
        
  default_users:
     ldap_manager_pw: {{ env['LDAP_MANAGER_PASSWORD'] }}
          
     administrators:
       - cn: admin
         firstname: Default
         surname: Admin
         password: {{ env['ADMIN_PASSWD'] }}
              
     endusers:
       - cn: {{ env['DEFAULT_USER'] }}
         firstname: {{ env['DEFAULT_USER_FIRSTNAME'] }}
         surname: {{ env['DEFAULT_USER_LASTNAME'] }}
         password: {{ env['DEFAULT_USER_PASSWD'] }}
         # HINT: Add additional users as a YAML array      
             
